server:
  port: 8081

spring:
  application:
    name: loja-online-pagamento-be

  rabbitmq:
    ost: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://loja-postgres:5432/loja
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

logging:
  level:
    root: INFO
    com.actdigital.lojaonlinepagamentobe: DEBUG
    org.springframework.amqp: INFO
